/**
 * Static badge image registry.
 * All require() calls must be statically analyzable for the Metro bundler.
 * Keyed by the numeric prefix from the filename (e.g. "011" → 011-compass.png).
 */
import { ImageSourcePropType } from 'react-native';

export const BADGE_IMAGES: Record<string, ImageSourcePropType> = {
  '001': require('../../assets/badges/001-accessory.png'),
  '002': require('../../assets/badges/002-goblin.png'),
  '003': require('../../assets/badges/003-money-bag.png'),
  '004': require('../../assets/badges/004-waiting.png'),
  '005': require('../../assets/badges/005-social-life.png'),
  '006': require('../../assets/badges/006-toy.png'),
  '007': require('../../assets/badges/007-home.png'),
  '008': require('../../assets/badges/008-baby.png'),
  '009': require('../../assets/badges/009-mouse.png'),
  '010': require('../../assets/badges/010-confetti.png'),
  '011': require('../../assets/badges/011-compass.png'),
  '012': require('../../assets/badges/012-expertise.png'),
  '013': require('../../assets/badges/013-vinyl.png'),
  '014': require('../../assets/badges/014-mask.png'),
  '015': require('../../assets/badges/015-weekend.png'),
  '016': require('../../assets/badges/016-wrench.png'),
  '017': require('../../assets/badges/017-scarf.png'),
  '018': require('../../assets/badges/018-peace.png'),
  '019': require('../../assets/badges/019-professional-services.png'),
  '020': require('../../assets/badges/020-magic-wand.png'),
  '021': require('../../assets/badges/021-mindset.png'),
  '022': require('../../assets/badges/022-house.png'),
  '023': require('../../assets/badges/023-ai-technology.png'),
  '024': require('../../assets/badges/024-climbing-stairs.png'),
  '025': require('../../assets/badges/025-level-up.png'),
  '026': require('../../assets/badges/026-gears.png'),
  '027': require('../../assets/badges/027-aniversary.png'),
  '028': require('../../assets/badges/028-phone-camera.png'),
  '029': require('../../assets/badges/029-camera.png'),
  '030': require('../../assets/badges/030-honeybee.png'),
  '031': require('../../assets/badges/031-star.png'),
  '032': require('../../assets/badges/032-fire.png'),
  '033': require('../../assets/badges/033-early.png'),
  '034': require('../../assets/badges/034-social-support.png'),
  '035': require('../../assets/badges/035-sunglasses.png'),
  '036': require('../../assets/badges/036-binocular.png'),
  '037': require('../../assets/badges/037-loyalty.png'),
  '038': require('../../assets/badges/038-plug.png'),
  '039': require('../../assets/badges/039-gem.png'),
  '040': require('../../assets/badges/040-lens.png'),
  '041': require('../../assets/badges/041-no-connection.png'),
  '042': require('../../assets/badges/042-test.png'),
  '043': require('../../assets/badges/043-choice.png'),
  '044': require('../../assets/badges/044-boat-captain-hat.png'),
  '045': require('../../assets/badges/045-diversity.png'),
  '046': require('../../assets/badges/046-rec.png'),
  '047': require('../../assets/badges/047-tongue.png'),
  '048': require('../../assets/badges/048-extract.png'),
  '049': require('../../assets/badges/049-leadership.png'),
  '050': require('../../assets/badges/050-coffee-bean.png'),
  '051': require('../../assets/badges/051-searcher.png'),
  '052': require('../../assets/badges/052-croissant.png'),
  '053': require('../../assets/badges/053-woman.png'),
  '054': require('../../assets/badges/054-self-love.png'),
  '055': require('../../assets/badges/055-makeover.png'),
  '056': require('../../assets/badges/056-nail-polish.png'),
  '057': require('../../assets/badges/057-lion.png'),
  '058': require('../../assets/badges/058-plant.png'),
  '059': require('../../assets/badges/059-heritage.png'),
  '060': require('../../assets/badges/060-history.png'),
  '061': require('../../assets/badges/061-master.png'),
  '062': require('../../assets/badges/062-decoration.png'),
  '063': require('../../assets/badges/063-easel.png'),
  '064': require('../../assets/badges/064-clapperboard.png'),
  '065': require('../../assets/badges/065-seeding.png'),
  '066': require('../../assets/badges/066-skydiving.png'),
  '067': require('../../assets/badges/067-adventure-game.png'),
  '068': require('../../assets/badges/068-trail-marker.png'),
  '069': require('../../assets/badges/069-wave.png'),
  '070': require('../../assets/badges/070-botanical.png'),
  '071': require('../../assets/badges/071-devil.png'),
  '072': require('../../assets/badges/072-jewel.png'),
  '073': require('../../assets/badges/073-shopaholic.png'),
  'default': require('../../assets/badges/default-badge.png'),
};

/** Resolve a badge image by its 3-digit key, falling back to default. */
export function getBadgeImage(imageKey: string): ImageSourcePropType {
  return BADGE_IMAGES[imageKey] ?? BADGE_IMAGES['default'];
}
