/**
 * Badge mappings for mobile — full parity with sayso-web/src/app/lib/badgeMappings.ts
 * imageKey matches the 3-digit prefix in assets/badges/ (e.g. "011" → 011-compass.png)
 */

export type BadgeGroup = 'explorer' | 'specialist' | 'milestone' | 'community';

export interface BadgeMappingItem {
  id: string;
  name: string;
  description: string;
  howToEarn: string;
  ionicon: string;
  imageKey: string;
  badgeGroup: BadgeGroup;
  categoryKey?: string;
}

export const BADGE_MAPPINGS: Record<string, BadgeMappingItem> = {
  // =============================================
  // A. EXPLORER BADGES
  // =============================================
  explorer_dabbler: {
    id: 'explorer_dabbler',
    name: 'The Dabbler',
    description: 'Dipping your toes into the community.',
    howToEarn: 'Write your first review.',
    ionicon: 'compass-outline',
    imageKey: '011',
    badgeGroup: 'explorer',
  },
  explorer_newbie_nomad: {
    id: 'explorer_newbie_nomad',
    name: 'Newbie Nomad',
    description: 'Starting to explore different categories.',
    howToEarn: 'Review businesses in 3 different categories.',
    ionicon: 'search-outline',
    imageKey: '036',
    badgeGroup: 'explorer',
  },
  explorer_curiosity_captain: {
    id: 'explorer_curiosity_captain',
    name: 'Curiosity Captain',
    description: 'Actively broadening your horizons.',
    howToEarn: 'Review businesses in 5 different categories.',
    ionicon: 'boat-outline',
    imageKey: '044',
    badgeGroup: 'explorer',
  },
  explorer_variety_voyager: {
    id: 'explorer_variety_voyager',
    name: 'Variety Voyager',
    description: "A true explorer of the city's offerings.",
    howToEarn: 'Review businesses in 8 different categories.',
    ionicon: 'globe-outline',
    imageKey: '045',
    badgeGroup: 'explorer',
  },
  explorer_full_circle: {
    id: 'explorer_full_circle',
    name: 'Full Circle',
    description: "You've seen it all.",
    howToEarn: 'Review businesses in all available categories.',
    ionicon: 'ellipse-outline',
    imageKey: '046',
    badgeGroup: 'explorer',
  },

  // =============================================
  // B. SPECIALIST — Food & Drink
  // =============================================
  specialist_food_taste_tester: {
    id: 'specialist_food_taste_tester',
    name: 'Taste Tester',
    description: 'Your palate is always ready.',
    howToEarn: 'Write 3 food & drink reviews.',
    ionicon: 'restaurant-outline',
    imageKey: '047',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_flavour_finder: {
    id: 'specialist_food_flavour_finder',
    name: 'Flavour Finder',
    description: 'Discovering hidden culinary gems.',
    howToEarn: 'Write 10 food & drink reviews.',
    ionicon: 'search-outline',
    imageKey: '017',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_foodie_boss: {
    id: 'specialist_food_foodie_boss',
    name: 'Foodie Boss',
    description: 'The undisputed authority on local dining.',
    howToEarn: 'Write 25 food & drink reviews.',
    ionicon: 'trophy-outline',
    imageKey: '049',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_coffee_connoisseur: {
    id: 'specialist_food_coffee_connoisseur',
    name: 'Coffee Connoisseur',
    description: 'Life runs on good coffee and honest reviews.',
    howToEarn: 'Write 5 café or coffee shop reviews.',
    ionicon: 'cafe-outline',
    imageKey: '050',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_dessert_detective: {
    id: 'specialist_food_dessert_detective',
    name: 'Dessert Detective',
    description: 'Always on the hunt for the perfect sweet treat.',
    howToEarn: 'Write 5 dessert or bakery reviews.',
    ionicon: 'ice-cream-outline',
    imageKey: '042',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_brunch_enthusiast: {
    id: 'specialist_food_brunch_enthusiast',
    name: 'Brunch Enthusiast',
    description: 'Weekend mornings are sacred.',
    howToEarn: 'Write 5 brunch spot reviews.',
    ionicon: 'sunny-outline',
    imageKey: '052',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },

  // =============================================
  // B. SPECIALIST — Beauty & Wellness
  // =============================================
  specialist_beauty_glow_getter: {
    id: 'specialist_beauty_glow_getter',
    name: 'Glow Getter',
    description: 'Always finding the best beauty spots.',
    howToEarn: 'Write 3 beauty & wellness reviews.',
    ionicon: 'sparkles-outline',
    imageKey: '053',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_self_care_superstar: {
    id: 'specialist_beauty_self_care_superstar',
    name: 'Self-Care Superstar',
    description: 'Self-care is a priority, and you lead by example.',
    howToEarn: 'Write 10 beauty & wellness reviews.',
    ionicon: 'heart-outline',
    imageKey: '054',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_beauty_boss: {
    id: 'specialist_beauty_beauty_boss',
    name: 'Beauty Boss',
    description: 'Reigning supreme in the world of beauty.',
    howToEarn: 'Write 25 beauty & wellness reviews.',
    ionicon: 'color-wand-outline',
    imageKey: '055',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_cuticle_queen: {
    id: 'specialist_beauty_cuticle_queen',
    name: 'Cuticle Queen',
    description: 'Nails it every single time.',
    howToEarn: 'Write 5 nail salon reviews.',
    ionicon: 'cut-outline',
    imageKey: '056',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_mane_lover: {
    id: 'specialist_beauty_mane_lover',
    name: 'Mane Lover',
    description: 'Hair game: always strong.',
    howToEarn: 'Write 5 hair salon reviews.',
    ionicon: 'color-palette-outline',
    imageKey: '057',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_serenity_seeker: {
    id: 'specialist_beauty_serenity_seeker',
    name: 'Serenity Seeker',
    description: 'Finding peace one spa review at a time.',
    howToEarn: 'Write 5 spa or wellness reviews.',
    ionicon: 'flower-outline',
    imageKey: '058',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },

  // =============================================
  // B. SPECIALIST — Arts & Culture
  // =============================================
  specialist_arts_heritage_hunter: {
    id: 'specialist_arts_heritage_hunter',
    name: 'Heritage Hunter',
    description: 'History and culture excite you.',
    howToEarn: 'Write 3 arts & culture reviews.',
    ionicon: 'business-outline',
    imageKey: '059',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_local_lore_seeker: {
    id: 'specialist_arts_local_lore_seeker',
    name: 'Local Lore Seeker',
    description: "You know this city's stories better than anyone.",
    howToEarn: 'Write 10 arts & culture reviews.',
    ionicon: 'book-outline',
    imageKey: '060',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_culture_master: {
    id: 'specialist_arts_culture_master',
    name: 'Culture Master',
    description: 'A true connoisseur of the arts.',
    howToEarn: 'Write 25 arts & culture reviews.',
    ionicon: 'school-outline',
    imageKey: '061',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_curtain_chaser: {
    id: 'specialist_arts_curtain_chaser',
    name: 'Curtain Chaser',
    description: 'If there is a show, you are there.',
    howToEarn: 'Write 5 theatre or performance reviews.',
    ionicon: 'film-outline',
    imageKey: '014',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_canvas_collector: {
    id: 'specialist_arts_canvas_collector',
    name: 'Canvas Collector',
    description: 'Galleries and exhibitions are your happy place.',
    howToEarn: 'Write 5 gallery or museum reviews.',
    ionicon: 'color-palette-outline',
    imageKey: '063',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_cinephile: {
    id: 'specialist_arts_cinephile',
    name: 'Cinephile',
    description: 'Two hours in the dark beats everything.',
    howToEarn: 'Write 5 cinema reviews.',
    ionicon: 'videocam-outline',
    imageKey: '064',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },

  // =============================================
  // B. SPECIALIST — Outdoors & Adventure
  // =============================================
  specialist_outdoors_nature_nomad: {
    id: 'specialist_outdoors_nature_nomad',
    name: 'Nature Nomad',
    description: 'At home in the great outdoors.',
    howToEarn: 'Write 3 outdoors & adventure reviews.',
    ionicon: 'leaf-outline',
    imageKey: '065',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_thrill_seeker: {
    id: 'specialist_outdoors_thrill_seeker',
    name: 'Thrill Seeker',
    description: 'Adrenaline is your love language.',
    howToEarn: 'Write 10 outdoors & adventure reviews.',
    ionicon: 'trending-up-outline',
    imageKey: '066',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_adventure_voyager: {
    id: 'specialist_outdoors_adventure_voyager',
    name: 'Adventure Voyager',
    description: 'Always chasing the next great experience.',
    howToEarn: 'Write 25 outdoors & adventure reviews.',
    ionicon: 'navigate-outline',
    imageKey: '067',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_trail_tamer: {
    id: 'specialist_outdoors_trail_tamer',
    name: 'Trail Tamer',
    description: 'No trail is too tough.',
    howToEarn: 'Write 5 hiking or trail reviews.',
    ionicon: 'map-outline',
    imageKey: '068',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_beach_bum: {
    id: 'specialist_outdoors_beach_bum',
    name: 'Beach Bum',
    description: 'Sand, sun, and honest reviews.',
    howToEarn: 'Write 5 beach or waterfront reviews.',
    ionicon: 'water-outline',
    imageKey: '069',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_botanical_buff: {
    id: 'specialist_outdoors_botanical_buff',
    name: 'Botanical Buff',
    description: 'Plants, parks, and fresh air.',
    howToEarn: 'Write 5 garden or park reviews.',
    ionicon: 'flower-outline',
    imageKey: '070',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_daredevil: {
    id: 'specialist_outdoors_daredevil',
    name: 'Daredevil',
    description: 'Fear is not in your vocabulary.',
    howToEarn: 'Write 5 extreme sports reviews.',
    ionicon: 'flame-outline',
    imageKey: '071',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },

  // =============================================
  // B. SPECIALIST — Shopping & Lifestyle
  // =============================================
  specialist_shopping_retail_royalty: {
    id: 'specialist_shopping_retail_royalty',
    name: 'Retail Royalty',
    description: 'Shopping is an art form.',
    howToEarn: 'Write 3 shopping & lifestyle reviews.',
    ionicon: 'bag-outline',
    imageKey: '072',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_shopaholic: {
    id: 'specialist_shopping_shopaholic',
    name: 'Shopaholic',
    description: 'Retail therapy is real therapy.',
    howToEarn: 'Write 10 shopping & lifestyle reviews.',
    ionicon: 'cart-outline',
    imageKey: '073',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_style_spotter: {
    id: 'specialist_shopping_style_spotter',
    name: 'Style Spotter',
    description: 'Fashion-forward and always on trend.',
    howToEarn: 'Write 5 clothing or accessories reviews.',
    ionicon: 'shirt-outline',
    imageKey: '001',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_gadget_goblin: {
    id: 'specialist_shopping_gadget_goblin',
    name: 'Gadget Goblin',
    description: 'You love tech more than most people.',
    howToEarn: 'Write 5 electronics or tech reviews.',
    ionicon: 'phone-portrait-outline',
    imageKey: '002',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_baddie_on_budget: {
    id: 'specialist_shopping_baddie_on_budget',
    name: 'Baddie on a Budget',
    description: 'Looking good without breaking the bank.',
    howToEarn: 'Write 5 value-for-money reviews.',
    ionicon: 'wallet-outline',
    imageKey: '003',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },

  // =============================================
  // B. SPECIALIST — Family & Pets
  // =============================================
  specialist_family_quality_time_seeker: {
    id: 'specialist_family_quality_time_seeker',
    name: 'Quality Time Seeker',
    description: 'Making every family moment count.',
    howToEarn: 'Write 3 family-friendly reviews.',
    ionicon: 'people-outline',
    imageKey: '004',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_bonding_buff: {
    id: 'specialist_family_bonding_buff',
    name: 'Bonding Buff',
    description: 'Family first, always.',
    howToEarn: 'Write 10 family-friendly reviews.',
    ionicon: 'heart-outline',
    imageKey: '018',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_playtime_pro: {
    id: 'specialist_family_playtime_pro',
    name: 'Playtime Pro',
    description: 'Finding the best spots for kids.',
    howToEarn: 'Write 5 kids or family activity reviews.',
    ionicon: 'game-controller-outline',
    imageKey: '006',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_care_companion: {
    id: 'specialist_family_care_companion',
    name: 'Care Companion',
    description: 'Always there for those who need it.',
    howToEarn: 'Write 5 care service reviews.',
    ionicon: 'heart-outline',
    imageKey: '005',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_play_paws: {
    id: 'specialist_family_play_paws',
    name: 'Play & Paws',
    description: 'Furry friends deserve the best too.',
    howToEarn: 'Write 5 pet-friendly business reviews.',
    ionicon: 'paw-outline',
    imageKey: '009',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_friendly_spaces_finder: {
    id: 'specialist_family_friendly_spaces_finder',
    name: 'Friendly Spaces Finder',
    description: 'Finding welcoming spaces for all.',
    howToEarn: 'Write 5 inclusive or accessible venue reviews.',
    ionicon: 'happy-outline',
    imageKey: '010',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },

  // =============================================
  // B. SPECIALIST — Experiences & Entertainment
  // =============================================
  specialist_experiences_memory_maker: {
    id: 'specialist_experiences_memory_maker',
    name: 'Memory Maker',
    description: 'Every outing becomes a story.',
    howToEarn: 'Write 3 experience & entertainment reviews.',
    ionicon: 'sparkles-outline',
    imageKey: '008',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_curiosity_cruiser: {
    id: 'specialist_experiences_curiosity_cruiser',
    name: 'Curiosity Cruiser',
    description: 'Always seeking something new.',
    howToEarn: 'Write 10 experience reviews.',
    ionicon: 'compass-outline',
    imageKey: '051',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_vibe_voyager: {
    id: 'specialist_experiences_vibe_voyager',
    name: 'Vibe Voyager',
    description: 'You can read a room instantly.',
    howToEarn: 'Write 25 experience reviews.',
    ionicon: 'radio-outline',
    imageKey: '043',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_beat_chaser: {
    id: 'specialist_experiences_beat_chaser',
    name: 'Beat Chaser',
    description: 'Always in the front row.',
    howToEarn: 'Write 5 music venue reviews.',
    ionicon: 'musical-notes-outline',
    imageKey: '013',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_show_goer: {
    id: 'specialist_experiences_show_goer',
    name: 'Show Goer',
    description: 'The curtain going up is your favourite sound.',
    howToEarn: 'Write 5 show or event reviews.',
    ionicon: 'ticket-outline',
    imageKey: '062',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_weekend_warrior: {
    id: 'specialist_experiences_weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Friday to Sunday is your kingdom.',
    howToEarn: 'Write 5 weekend event reviews.',
    ionicon: 'calendar-outline',
    imageKey: '015',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },

  // =============================================
  // B. SPECIALIST — Professional Services
  // =============================================
  specialist_services_service_scout: {
    id: 'specialist_services_service_scout',
    name: 'Service Scout',
    description: 'Hunting down the best service providers.',
    howToEarn: 'Write 3 professional service reviews.',
    ionicon: 'briefcase-outline',
    imageKey: '019',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_solution_seeker: {
    id: 'specialist_services_solution_seeker',
    name: 'Solution Seeker',
    description: 'No problem is unsolvable with the right service.',
    howToEarn: 'Write 10 professional service reviews.',
    ionicon: 'bulb-outline',
    imageKey: '048',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_service_pro: {
    id: 'specialist_services_service_pro',
    name: 'Service Pro',
    description: 'You know great service when you see it.',
    howToEarn: 'Write 25 professional service reviews.',
    ionicon: 'ribbon-outline',
    imageKey: '012',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_fix_it_fairy: {
    id: 'specialist_services_fix_it_fairy',
    name: 'Fix-It Fairy',
    description: 'You always find someone who can sort it out.',
    howToEarn: 'Write 5 repair or trade service reviews.',
    ionicon: 'construct-outline',
    imageKey: '016',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_money_minded: {
    id: 'specialist_services_money_minded',
    name: 'Money-Minded',
    description: 'Finance and value go hand in hand.',
    howToEarn: 'Write 5 financial service reviews.',
    ionicon: 'cash-outline',
    imageKey: '021',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_home_helper: {
    id: 'specialist_services_home_helper',
    name: 'Home Helper',
    description: 'Your home is always in good hands.',
    howToEarn: 'Write 5 home service reviews.',
    ionicon: 'home-outline',
    imageKey: '022',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },

  // =============================================
  // C. MILESTONE BADGES
  // =============================================
  milestone_new_voice: {
    id: 'milestone_new_voice',
    name: 'New Voice',
    description: 'Your journey begins with a single review.',
    howToEarn: 'Write your first review.',
    ionicon: 'mic-outline',
    imageKey: '023',
    badgeGroup: 'milestone',
  },
  milestone_rookie_reviewer: {
    id: 'milestone_rookie_reviewer',
    name: 'Rookie Reviewer',
    description: "Five reviews in — you're on a roll.",
    howToEarn: 'Write 5 reviews.',
    ionicon: 'trending-up-outline',
    imageKey: '024',
    badgeGroup: 'milestone',
  },
  milestone_level_up: {
    id: 'milestone_level_up',
    name: 'Level Up!',
    description: 'Ten reviews strong.',
    howToEarn: 'Write 10 reviews.',
    ionicon: 'bar-chart-outline',
    imageKey: '025',
    badgeGroup: 'milestone',
  },
  milestone_review_machine: {
    id: 'milestone_review_machine',
    name: 'Review Machine',
    description: 'Twenty-five reviews and still going.',
    howToEarn: 'Write 25 reviews.',
    ionicon: 'cog-outline',
    imageKey: '026',
    badgeGroup: 'milestone',
  },
  milestone_century_club: {
    id: 'milestone_century_club',
    name: 'Century Club',
    description: '100 reviews. An absolute legend.',
    howToEarn: 'Write 100 reviews.',
    ionicon: 'trophy-outline',
    imageKey: '027',
    badgeGroup: 'milestone',
  },
  milestone_picture_pioneer: {
    id: 'milestone_picture_pioneer',
    name: 'Picture Pioneer',
    description: 'A picture is worth a thousand words.',
    howToEarn: 'Add photos to 5 reviews.',
    ionicon: 'phone-portrait-outline',
    imageKey: '028',
    badgeGroup: 'milestone',
  },
  milestone_snapshot_superstar: {
    id: 'milestone_snapshot_superstar',
    name: 'Snapshot Superstar',
    description: 'Your photos help others choose.',
    howToEarn: 'Add photos to 25 reviews.',
    ionicon: 'camera-outline',
    imageKey: '029',
    badgeGroup: 'milestone',
  },
  milestone_helpful_honeybee: {
    id: 'milestone_helpful_honeybee',
    name: 'Helpful Honeybee',
    description: 'Your reviews are genuinely useful.',
    howToEarn: 'Receive 10 helpful votes.',
    ionicon: 'thumbs-up-outline',
    imageKey: '030',
    badgeGroup: 'milestone',
  },
  milestone_consistency_star: {
    id: 'milestone_consistency_star',
    name: 'Consistency Star',
    description: 'Showing up regularly for the community.',
    howToEarn: 'Write reviews in 3 consecutive months.',
    ionicon: 'star-outline',
    imageKey: '031',
    badgeGroup: 'milestone',
  },
  milestone_streak_spark: {
    id: 'milestone_streak_spark',
    name: 'Streak Spark',
    description: 'The fire is real.',
    howToEarn: 'Write reviews for 7 consecutive days.',
    ionicon: 'flash-outline',
    imageKey: '032',
    badgeGroup: 'milestone',
  },

  // =============================================
  // D. COMMUNITY BADGES
  // =============================================
  community_early_birdie: {
    id: 'community_early_birdie',
    name: 'Early Birdie',
    description: 'You were here before it was cool.',
    howToEarn: 'Join in the first 90 days of launch.',
    ionicon: 'sunny-outline',
    imageKey: '033',
    badgeGroup: 'community',
  },
  community_community_helper: {
    id: 'community_community_helper',
    name: 'Community Helper',
    description: 'Putting others first.',
    howToEarn: 'Receive 50 helpful votes.',
    ionicon: 'hand-left-outline',
    imageKey: '034',
    badgeGroup: 'community',
  },
  community_trend_starter: {
    id: 'community_trend_starter',
    name: 'Trend Starter',
    description: 'Always one step ahead of the crowd.',
    howToEarn: 'Be the first to review 5 businesses.',
    ionicon: 'trending-up-outline',
    imageKey: '035',
    badgeGroup: 'community',
  },
  community_columbus: {
    id: 'community_columbus',
    name: 'Columbus',
    description: 'A born explorer of the unknown.',
    howToEarn: 'Be the first to review 10 businesses.',
    ionicon: 'compass-outline',
    imageKey: '020',
    badgeGroup: 'community',
  },
  community_loyal_one: {
    id: 'community_loyal_one',
    name: 'The Loyal One',
    description: 'Consistency is your superpower.',
    howToEarn: 'Review for 6 consecutive months.',
    ionicon: 'repeat-outline',
    imageKey: '037',
    badgeGroup: 'community',
  },
  community_neighbourhood_plug: {
    id: 'community_neighbourhood_plug',
    name: 'Neighbourhood Plug',
    description: 'The go-to person for local recs.',
    howToEarn: 'Receive 100 helpful votes.',
    ionicon: 'location-outline',
    imageKey: '007',
    badgeGroup: 'community',
  },
  community_hidden_gem_hunter: {
    id: 'community_hidden_gem_hunter',
    name: 'Hidden Gem Hunter',
    description: 'Finding magic where others overlook it.',
    howToEarn: 'Discover and review 10 under-reviewed businesses.',
    ionicon: 'diamond-outline',
    imageKey: '039',
    badgeGroup: 'community',
  },
  community_lens_legend: {
    id: 'community_lens_legend',
    name: 'Lens Legend',
    description: 'Your photography elevates every review.',
    howToEarn: 'Add 50 photos across your reviews.',
    ionicon: 'aperture-outline',
    imageKey: '040',
    badgeGroup: 'community',
  },
  community_off_the_grid: {
    id: 'community_off_the_grid',
    name: 'Off the Grid',
    description: 'Shining a light on businesses the internet forgot.',
    howToEarn: 'Review 5 businesses with no prior online reviews.',
    ionicon: 'wifi-outline',
    imageKey: '041',
    badgeGroup: 'community',
  },
  community_plug_of_year: {
    id: 'community_plug_of_year',
    name: 'Plug of the Year',
    description: 'The community voted, you won.',
    howToEarn: 'Be recognised as a top contributor for the year.',
    ionicon: 'medal-outline',
    imageKey: '038',
    badgeGroup: 'community',
  },
};

export const BADGE_GROUPS: BadgeGroup[] = ['explorer', 'specialist', 'milestone', 'community'];

export function getBadgeById(id: string): BadgeMappingItem | undefined {
  return BADGE_MAPPINGS[id];
}

export function getBadgesByGroup(group: BadgeGroup): BadgeMappingItem[] {
  return Object.values(BADGE_MAPPINGS).filter((b) => b.badgeGroup === group);
}
